### ISSUE TITLE
# 引入 CaptureSDK 运行报错

### ISSUE THREAD

**Issue by cpken** [wunan96nj/3d-mapping-localization-GPS#1]
# 引入 CaptureSDK 运行报错

`test.py` 代码
```python
# coding=utf-8
import CaptureSDK

url = "http://localhost:5444"
api_url = url + '/capture-photo'
token = ''
uploadImagePath = './images/P1180141.JPG'
bank = 0
username = 'sample_user'
password = 'pass'

CaptureSDK.QueryLocal(api_url, token, uploadImagePath, bank, username, password)
```

报错内容

```
(venv) root@depthserver:/www/wwwroot/3d-mapping-localization-GPS-main/client# python test.py
http://localhost:5444/capture-photo
Traceback (most recent call last):
  File "/www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/venv/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    CaptureSDK.QueryLocal(api_url, token, uploadImagePath, bank, username, password)
  File "/www/wwwroot/3d-mapping-localization-GPS-main/client/CaptureSDK.py", line 140, in QueryLocal
    return_obj = json.loads(requests.post(complete_url, data=json_data, auth=(username, password)).json())
  File "/www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/venv/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

我已安装的 package

- numpy
- flask
- Flask-HTTPAuth
- environs
- pymap3d
- flask_restful
- opencv-python
- scipy
- open3d
- easy-pil

请问如何解决，谢谢。

**Comment by cpken** [comment]
我已经运行了 `3d-mapping-localization-main/CaptureApi.py` 服务端了
服务端报的错

```
QueryLocal BEGIN,
workspace_dir: /www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/sample_user/workspace-0/
image_base_dir: /www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/sample_user/workspace-0/images/
json_base_dir: /www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/sample_user/workspace-0/json/
sparse_dir: /www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/sample_user/workspace-0/sparse/
database_dir: /www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/sample_user/workspace-0/sparse/
col_bin_dir: /www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/sample_user/workspace-0/sparse/0/
QueryLocal image_name_prefix: P1180141
QueryLocal upload_image_file_full_path: /www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/sample_user/workspace-0/sparse/upload_temp/P1180141.jpg
QueryLocal upload_database_file_full_path: /www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/sample_user/workspace-0/sparse/upload_temp/P1180141.db
QueryLocal save_image() start .....
write image file to /www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/sample_user/workspace-0/sparse/upload_temp/P1180141.jpg
QueryLocal get_feature_upload() start .....
QueryLocal get_feature_upload() database_name: P1180141.db
QueryLocal get_feature_upload() upload_image_tmp_dir: /www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/sample_user/workspace-0/sparse/upload_temp/
1. feature_extractor
INFO - 2022-08-12 07:21:45,367 - _internal - 127.0.0.1 - - [12/Aug/2022 07:21:45] "POST /capture-photo/querylocal HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/venv/lib/python3.8/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/venv/lib/python3.8/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/CaptureApi.py", line 183, in QueryLocal
    QueryLocalUtil.get_feature_upload(COLMAP, image_name_prefix + ".db",
  File "/www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/map3d/util/QueryLocalUtil.py", line 30, in get_feature_upload
    Utils.feature_colmap(COLMAP, database_name, upload_image_tmp_dir,
  File "/www/wwwroot/3d-mapping-localization-GPS-main/3dmapping-localization-main/map3d/util/Utils.py", line 243, in feature_colmap
    pIntrisics = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'colmap'
```

**Comment by cpken** [comment]
建议编写一份项目部署文档（Ubuntu），需要使用哪些 package，安装的脚本，诸如此类的。
